import { Compass, Palmtree, Waves, Droplets, Tent, PartyPopper, MountainIcon } from "lucide-react"

export const tourCategories = [
  {
    id: "cultural",
    name: "Cultural & Heritage",
    icon: <Compass className="h-5 w-5 text-maroon-700" />,
    activities: [
      {
        id: "anuradhapura",
        name: "Anuradhapura",
        description: "The ancient capital, home to sacred Bodhi Tree and massive stupas.",
        image: "/placeholder.svg?height=400&width=600&text=Anuradhapura",
        images: [
          "/placeholder.svg?height=600&width=800&text=Anuradhapura+1",
          "/placeholder.svg?height=600&width=800&text=Anuradhapura+2",
          "/placeholder.svg?height=600&width=800&text=Anuradhapura+3",
          "/placeholder.svg?height=600&width=800&text=Anuradhapura+4",
        ],
        highlights: [
          "Sacred Bodhi Tree - Oldest historically authenticated tree in the world",
          "Ruwanwelisaya - Magnificent white stupa built in 140 B.C.",
          "Jetavanaramaya - Once the tallest stupa in the ancient world",
          "Thuparamaya - First stupa built in Sri Lanka after Buddhism introduction",
        ],
        bestTime: "Year-round, but December to March offers the most pleasant weather.",
      },
      {
        id: "polonnaruwa",
        name: "Polonnaruwa",
        description: "UNESCO site showcasing well-preserved ruins of medieval Sri Lanka.",
        image: "/placeholder.svg?height=400&width=600&text=Polonnaruwa",
        images: [
          "/placeholder.svg?height=600&width=800&text=Polonnaruwa+1",
          "/placeholder.svg?height=600&width=800&text=Polonnaruwa+2",
          "/placeholder.svg?height=600&width=800&text=Polonnaruwa+3",
          "/placeholder.svg?height=600&width=800&text=Polonnaruwa+4",
        ],
        highlights: [
          "Gal Vihara - Rock temple with magnificent Buddha statues",
          "Royal Palace - Impressive ruins of King Parakramabahu's residence",
          "Sacred Quadrangle - Compact group of fascinating ancient structures",
          "Parakrama Samudra - Ancient man-made reservoir still in use today",
        ],
        bestTime: "Year-round, but the dry season (May to September) is ideal.",
      },
      {
        id: "dambulla",
        name: "Dambulla Rock Cave Temple",
        description: "A spiritual cave temple with Buddhist murals and statues.",
        image: "/placeholder.svg?height=400&width=600&text=Dambulla",
        images: [
          "/placeholder.svg?height=600&width=800&text=Dambulla+1",
          "/placeholder.svg?height=600&width=800&text=Dambulla+2",
          "/placeholder.svg?height=600&width=800&text=Dambulla+3",
          "/placeholder.svg?height=600&width=800&text=Dambulla+4",
        ],
        highlights: [
          "Five caves containing 153 Buddha statues and hundreds of paintings",
          "Golden Temple - Massive golden Buddha statue at the entrance",
          "Cave of the Divine King - Largest and most impressive cave",
          "Ancient murals covering 2,100 square meters of cave walls",
        ],
        bestTime: "Year-round, but avoid the monsoon season (October to January).",
      },
      {
        id: "sigiriya",
        name: "Sigiriya",
        description: "Iconic Lion Rock fortress with frescoes and royal gardens.",
        image: "/placeholder.svg?height=400&width=600&text=Sigiriya",
        images: [
          "/placeholder.svg?height=600&width=800&text=Sigiriya+1",
          "/placeholder.svg?height=600&width=800&text=Sigiriya+2",
          "/placeholder.svg?height=600&width=800&text=Sigiriya+3",
          "/placeholder.svg?height=600&width=800&text=Sigiriya+4",
        ],
        highlights: [
          "Lion's Paw Entrance - Massive stone lion paws guarding the final ascent",
          "Ancient Frescoes - Well-preserved 5th-century paintings",
          "Mirror Wall - Ancient graffiti dating back 1,000 years",
          "Water Gardens - Sophisticated hydraulic systems still functioning today",
        ],
        bestTime: "Early morning (opens at 7 AM) to avoid crowds and heat.",
      },
      {
        id: "kandy",
        name: "Kandy",
        description: "Sacred city with the Temple of the Tooth and vibrant cultural shows.",
        image: "/placeholder.svg?height=400&width=600&text=Kandy",
        images: [
          "/placeholder.svg?height=600&width=800&text=Kandy+1",
          "/placeholder.svg?height=600&width=800&text=Kandy+2",
          "/placeholder.svg?height=600&width=800&text=Kandy+3",
          "/placeholder.svg?height=600&width=800&text=Kandy+4",
        ],
        highlights: [
          "Temple of the Sacred Tooth Relic - Most revered Buddhist site in Sri Lanka",
          "Kandy Lake - Scenic artificial lake built in 1807",
          "Royal Botanical Gardens - 147-acre garden with over 4,000 species",
          "Traditional Kandyan Dance performances every evening",
        ],
        bestTime: "January to April for the best weather, or July/August for the Esala Perahera festival.",
      },
    ],
  },
  {
    id: "wildlife",
    name: "Wildlife Safaris & Nature Reserves",
    icon: <Palmtree className="h-5 w-5 text-maroon-700" />,
    activities: [
      {
        id: "yala",
        name: "Yala National Park",
        description: "Renowned for leopard sightings and diverse wildlife.",
        image: "/placeholder.svg?height=400&width=600&text=Yala",
        images: [
          "/placeholder.svg?height=600&width=800&text=Yala+1",
          "/placeholder.svg?height=600&width=800&text=Yala+2",
          "/placeholder.svg?height=600&width=800&text=Yala+3",
          "/placeholder.svg?height=600&width=800&text=Yala+4",
        ],
        highlights: [
          "Leopard spotting - Highest density of leopards in the world",
          "Diverse wildlife including elephants, sloth bears, and crocodiles",
          "Over 215 bird species, including 6 endemic to Sri Lanka",
          "Varied landscapes from forests to lagoons and coastlines",
        ],
        bestTime: "February to July when water levels are low and animals gather around water holes.",
      },
      {
        id: "wilpattu",
        name: "Wilpattu National Park",
        description: "Largest national park with natural lakes and untouched forest.",
        image: "/placeholder.svg?height=400&width=600&text=Wilpattu",
        images: [
          "/placeholder.svg?height=600&width=800&text=Wilpattu+1",
          "/placeholder.svg?height=600&width=800&text=Wilpattu+2",
          "/placeholder.svg?height=600&width=800&text=Wilpattu+3",
          "/placeholder.svg?height=600&width=800&text=Wilpattu+4",
        ],
        highlights: [
          "Natural lakes (Villus) - Unique feature of this national park",
          "Leopard sightings in natural, less crowded environment",
          "Sloth bears, elephants, and spotted deer",
          "Over 30 species of mammals and numerous bird species",
        ],
        bestTime: "February to October during the dry season.",
      },
      {
        id: "minneriya",
        name: "Minneriya National Park",
        description: "Home to 'The Gathering' – world's largest elephant meeting.",
        image: "/placeholder.svg?height=400&width=600&text=Minneriya",
        images: [
          "/placeholder.svg?height=600&width=800&text=Minneriya+1",
          "/placeholder.svg?height=600&width=800&text=Minneriya+2",
          "/placeholder.svg?height=600&width=800&text=Minneriya+3",
          "/placeholder.svg?height=600&width=800&text=Minneriya+4",
        ],
        highlights: [
          "The Gathering - Up to 300 elephants congregate around the reservoir",
          "Bird watching - Over 160 species of birds including endemic species",
          "Scenic landscapes - Grasslands, scrublands, and tank (reservoir)",
          "Other wildlife - Sambar deer, sloth bears, and leopards",
        ],
        bestTime: "August to October for 'The Gathering' when elephants congregate.",
      },
      {
        id: "sinharaja",
        name: "Sinharaja Rainforest",
        description: "UNESCO biosphere with endemic flora and fauna.",
        image: "/placeholder.svg?height=400&width=600&text=Sinharaja",
        images: [
          "/placeholder.svg?height=600&width=800&text=Sinharaja+1",
          "/placeholder.svg?height=600&width=800&text=Sinharaja+2",
          "/placeholder.svg?height=600&width=800&text=Sinharaja+3",
          "/placeholder.svg?height=600&width=800&text=Sinharaja+4",
        ],
        highlights: [
          "Biodiversity Hotspot - Over 60% of the trees are endemic to Sri Lanka",
          "Bird Watching - Home to 95% of Sri Lanka's endemic birds",
          "Mixed Species Bird Flocks - Unique phenomenon of different species hunting together",
          "Rare Amphibians - Including the endangered purple-faced langur",
        ],
        bestTime: "January to April and August to September for drier conditions.",
      },
    ],
  },
  {
    id: "beach",
    name: "Beach & Coastal Tours",
    icon: <Waves className="h-5 w-5 text-maroon-700" />,
    activities: [
      {
        id: "hikkaduwa",
        name: "Hikkaduwa",
        description: "Famous for coral reefs and vibrant nightlife.",
        image: "/placeholder.svg?height=400&width=600&text=Hikkaduwa",
        images: [
          "/placeholder.svg?height=600&width=800&text=Hikkaduwa+1",
          "/placeholder.svg?height=600&width=800&text=Hikkaduwa+2",
          "/placeholder.svg?height=600&width=800&text=Hikkaduwa+3",
          "/placeholder.svg?height=600&width=800&text=Hikkaduwa+4",
        ],
        highlights: [
          "Coral Sanctuary - Snorkel among colorful fish and sea turtles",
          "Beach Parties - Vibrant nightlife with beachfront bars and restaurants",
          "Surfing - Consistent waves suitable for beginners and intermediate surfers",
          "Moonstone Mines - Visit nearby traditional moonstone mines",
        ],
        bestTime: "November to April for the best beach weather and water clarity.",
      },
      {
        id: "arugambay",
        name: "Arugam Bay",
        description: "Surfer's paradise with beach vibes and scenic views.",
        image: "/placeholder.svg?height=400&width=600&text=Arugam+Bay",
        images: [
          "/placeholder.svg?height=600&width=800&text=Arugam+Bay+1",
          "/placeholder.svg?height=600&width=800&text=Arugam+Bay+2",
          "/placeholder.svg?height=600&width=800&text=Arugam+Bay+3",
          "/placeholder.svg?height=600&width=800&text=Arugam+Bay+4",
        ],
        highlights: [
          "World-class surfing with multiple point breaks",
          "Laid-back beach atmosphere with bohemian vibes",
          "Nearby wildlife including elephants occasionally visiting the area",
          "Beautiful sunrises over the Indian Ocean",
        ],
        bestTime: "April to October for the best surfing conditions.",
      },
      {
        id: "mirissa",
        name: "Mirissa",
        description: "Whale watching, beach parties, and scenic palm hill.",
        image: "/placeholder.svg?height=400&width=600&text=Mirissa",
        images: [
          "/placeholder.svg?height=600&width=800&text=Mirissa+1",
          "/placeholder.svg?height=600&width=800&text=Mirissa+2",
          "/placeholder.svg?height=600&width=800&text=Mirissa+3",
          "/placeholder.svg?height=600&width=800&text=Mirissa+4",
        ],
        highlights: [
          "Whale watching - Blue whales and sperm whales",
          "Coconut Tree Hill - Iconic viewpoint for sunset photos",
          "Pristine beaches with clear turquoise waters",
          "Vibrant nightlife with beachfront restaurants and bars",
        ],
        bestTime: "November to April for whale watching and best beach weather.",
      },
      {
        id: "turtlehatchery",
        name: "Turtle Hatchery",
        description: "Conservation sites helping baby turtles reach the ocean.",
        image: "/placeholder.svg?height=400&width=600&text=Turtle+Hatchery",
        images: [
          "/placeholder.svg?height=600&width=800&text=Turtle+Hatchery+1",
          "/placeholder.svg?height=600&width=800&text=Turtle+Hatchery+2",
          "/placeholder.svg?height=600&width=800&text=Turtle+Hatchery+3",
          "/placeholder.svg?height=600&width=800&text=Turtle+Hatchery+4",
        ],
        highlights: [
          "Conservation Efforts - Learn about turtle protection programs",
          "Baby Turtles - See newly hatched turtles before their release",
          "Injured Turtles - Visit rehabilitation tanks for injured sea turtles",
          "Turtle Release - Participate in releasing baby turtles into the ocean (seasonal)",
        ],
        bestTime: "Year-round, but turtle hatching is most common from January to July.",
      },
    ],
  },
  {
    id: "water",
    name: "Water-Based Activities",
    icon: <Droplets className="h-5 w-5 text-maroon-700" />,
    activities: [
      {
        id: "kitulgala",
        name: "Kitulgala",
        description: "White-water rafting and rainforest hikes.",
        image: "/placeholder.svg?height=400&width=600&text=Kitulgala",
        images: [
          "/placeholder.svg?height=600&width=800&text=Kitulgala+1",
          "/placeholder.svg?height=600&width=800&text=Kitulgala+2",
          "/placeholder.svg?height=600&width=800&text=Kitulgala+3",
          "/placeholder.svg?height=600&width=800&text=Kitulgala+4",
        ],
        highlights: [
          "White water rafting on the Kelani River with Grade 2-4 rapids",
          "Jungle trekking through dense rainforest",
          "Waterfall abseiling and canyoning adventures",
          "Bridge on the River Kwai filming location",
        ],
        bestTime: "May to December when water levels are optimal for rafting.",
      },
      {
        id: "maduganga",
        name: "Madu Ganga",
        description: "Tranquil mangrove river with boat safaris.",
        image: "/placeholder.svg?height=400&width=600&text=Madu+Ganga",
        images: [
          "/placeholder.svg?height=600&width=800&text=Madu+Ganga+1",
          "/placeholder.svg?height=600&width=800&text=Madu+Ganga+2",
          "/placeholder.svg?height=600&width=800&text=Madu+Ganga+3",
          "/placeholder.svg?height=600&width=800&text=Madu+Ganga+4",
        ],
        highlights: [
          "Boat safari through intricate mangrove forests",
          "Visit to Cinnamon Island to see traditional processing",
          "Fish therapy (natural fish spa) in designated areas",
          "Rich biodiversity with birds, monitor lizards, and monkeys",
        ],
        bestTime: "Year-round, but the dry season (December to April) is most comfortable.",
      },
    ],
  },
  {
    id: "adventure",
    name: "Adventure & Hiking",
    icon: <Tent className="h-5 w-5 text-maroon-700" />,
    activities: [
      {
        id: "adamspeak",
        name: "Adam's Peak",
        description: "Sacred mountain climb with sunrise views and religious significance.",
        image: "/placeholder.svg?height=400&width=600&text=Adams+Peak",
        images: [
          "/placeholder.svg?height=600&width=800&text=Adams+Peak+1",
          "/placeholder.svg?height=600&width=800&text=Adams+Peak+2",
          "/placeholder.svg?height=600&width=800&text=Adams+Peak+3",
          "/placeholder.svg?height=600&width=800&text=Adams+Peak+4",
        ],
        highlights: [
          "Sacred footprint (Sri Pada) revered by multiple religions",
          "Spectacular sunrise views and shadow of the peak",
          "Night climb with illuminated path during pilgrimage season",
          "Sense of achievement upon reaching the 2,243m summit",
        ],
        bestTime: "Pilgrimage season from December to May when the path is illuminated.",
      },
      {
        id: "ellarock",
        name: "Ella Rock",
        description: "Scenic hike with valley views and peaceful paths.",
        image: "/placeholder.svg?height=400&width=600&text=Ella+Rock",
        images: [
          "/placeholder.svg?height=600&width=800&text=Ella+Rock+1",
          "/placeholder.svg?height=600&width=800&text=Ella+Rock+2",
          "/placeholder.svg?height=600&width=800&text=Ella+Rock+3",
          "/placeholder.svg?height=600&width=800&text=Ella+Rock+4",
        ],
        highlights: [
          "Panoramic views of Ella Gap and surrounding mountains",
          "Moderate 4-hour round trip hike through tea plantations",
          "Peaceful environment away from crowds",
          "Opportunity to see local flora and fauna",
        ],
        bestTime: "Early morning for the best views and cooler temperatures.",
      },
    ],
  },
  {
    id: "festivals",
    name: "Festivals & Cultural Events",
    icon: <PartyPopper className="h-5 w-5 text-maroon-700" />,
    activities: [
      {
        id: "vesak",
        name: "Vesak Festival",
        description: "Lantern-filled festival celebrating Buddha's birth, enlightenment, and death.",
        image: "/placeholder.svg?height=400&width=600&text=Vesak",
        images: [
          "/placeholder.svg?height=600&width=800&text=Vesak+1",
          "/placeholder.svg?height=600&width=800&text=Vesak+2",
          "/placeholder.svg?height=600&width=800&text=Vesak+3",
          "/placeholder.svg?height=600&width=800&text=Vesak+4",
        ],
        highlights: [
          "Colorful lanterns illuminating streets and homes",
          "Pandals - large illuminated panels depicting Buddhist stories",
          "Free food and drink stalls (dansal) throughout the country",
          "Temples filled with devotees and beautiful decorations",
        ],
        bestTime: "Full moon day in May (dates vary each year).",
      },
      {
        id: "perahera",
        name: "Kandy Esala Perahera",
        description: "Majestic Kandy procession with decorated elephants and dancers.",
        image: "/placeholder.svg?height=400&width=600&text=Esala+Perahera",
        images: [
          "/placeholder.svg?height=600&width=800&text=Esala+Perahera+1",
          "/placeholder.svg?height=600&width=800&text=Esala+Perahera+2",
          "/placeholder.svg?height=600&width=800&text=Esala+Perahera+3",
          "/placeholder.svg?height=600&width=800&text=Esala+Perahera+4",
        ],
        highlights: [
          "Over 100 elegantly decorated elephants in procession",
          "Traditional Kandyan dancers and drummers",
          "Fire dancers and whip crackers creating spectacle",
          "Sacred Tooth Relic casket carried on lead elephant",
        ],
        bestTime: "Ten days ending on the full moon in July or August (dates vary each year).",
      },
    ],
  },
  {
    id: "scenic",
    name: "Scenic & Upcountry Escapes",
    icon: <MountainIcon className="h-5 w-5 text-maroon-700" />,
    activities: [
      {
        id: "nuwaraeliya",
        name: "Nuwara Eliya",
        description: "Colonial-style town known as 'Little England'.",
        image: "/placeholder.svg?height=400&width=600&text=Nuwara+Eliya",
        images: [
          "/placeholder.svg?height=600&width=800&text=Nuwara+Eliya+1",
          "/placeholder.svg?height=600&width=800&text=Nuwara+Eliya+2",
          "/placeholder.svg?height=600&width=800&text=Nuwara+Eliya+3",
          "/placeholder.svg?height=600&width=800&text=Nuwara+Eliya+4",
        ],
        highlights: [
          "Colonial architecture and English-style gardens",
          "Tea plantations with factory tours and tastings",
          "Gregory Lake with boating and recreational activities",
          "Horton Plains National Park and World's End nearby",
        ],
        bestTime: "March to May for the best weather, or April for the Sinhala New Year celebrations.",
      },
      {
        id: "ella",
        name: "Ella",
        description: "Lush hill town with hikes, cafes, and breathtaking scenery.",
        image: "/placeholder.svg?height=400&width=600&text=Ella",
        images: [
          "/placeholder.svg?height=600&width=800&text=Ella+1",
          "/placeholder.svg?height=600&width=800&text=Ella+2",
          "/placeholder.svg?height=600&width=800&text=Ella+3",
          "/placeholder.svg?height=600&width=800&text=Ella+4",
        ],
        highlights: [
          "Nine Arch Bridge - Iconic colonial-era railway bridge",
          "Little Adam's Peak - Easy hike with panoramic views",
          "Ravana Falls - Beautiful waterfall with mythological significance",
          "Scenic train journey from Ella to Kandy",
        ],
        bestTime: "January to March for the driest weather and clearest views.",
      },
    ],
  },
]
